"""add_is_verified_to_users

Revision ID: 558a12a0de8e
Revises: 6e2eb1a88625
Create Date: 2026-06-26 13:29:09.889606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558a12a0de8e'
down_revision: Union[str, Sequence[str], None] = '6e2eb1a88625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # Mark all existing users as verified so they aren't locked out
    op.execute("UPDATE users SET is_verified = true")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
