"""add_is_active_to_analyses

Revision ID: cef65b1cadeb
Revises: 570ae94a2863
Create Date: 2026-06-26 01:50:22.163167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef65b1cadeb'
down_revision: Union[str, Sequence[str], None] = '570ae94a2863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_analyses_is_active'), 'analyses', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_is_active'), table_name='analyses')
    op.drop_column('analyses', 'is_active')
    # ### end Alembic commands ###
