"""add_edited_body_to_analysis_cover_letters

Revision ID: 76f79cdc8a99
Revises: 39af70b5480d
Create Date: 2026-08-28 13:17:27.927111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f79cdc8a99'
down_revision: Union[str, Sequence[str], None] = '39af70b5480d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_cover_letters', sa.Column('edited_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_cover_letters', 'edited_body')
    # ### end Alembic commands ###
