"""drop_application_steps

Revision ID: b49e40f10120
Revises: dbe12f03202f
Create Date: 2026-08-27 13:25:09.272286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b49e40f10120'
down_revision: Union[str, Sequence[str], None] = 'dbe12f03202f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_steps_application_id'), table_name='application_steps')
    op.drop_table('application_steps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_steps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'applied'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('application_steps_application_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('application_steps_pkey'))
    )
    op.create_index(op.f('ix_application_steps_application_id'), 'application_steps', ['application_id'], unique=False)
    # ### end Alembic commands ###
