"""add edited_body to applications

Revision ID: b6cfbe9ac426
Revises: 76f79cdc8a99
Create Date: 2026-08-28 20:34:52.513728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cfbe9ac426'
down_revision: Union[str, Sequence[str], None] = '76f79cdc8a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('edited_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'edited_body')
    # ### end Alembic commands ###
