# Job seed keywords organized by domain.
# Source: curated from ROME (France Travail) and ESCO (European Commission) taxonomies.
# Used by the Cortex ingestion worker to build a generalist job index.
# Each entry is a short, searchable job title usable directly on job boards (JSearch, Adzuna).

SEED_KEYWORDS_BY_DOMAIN: dict[str, list[str]] = {
    "tech_software": [
        "software engineer",
        "backend developer",
        "frontend developer",
        "fullstack developer",
        "mobile developer",
        "iOS developer",
        "Android developer",
        "web developer",
        "software architect",
        "tech lead",
    ],
    "tech_data": [
        "data engineer",
        "data scientist",
        "data analyst",
        "business intelligence",
        "ML engineer",
        "AI engineer",
        "NLP engineer",
        "MLOps engineer",
        "data architect",
        "analytics engineer",
    ],
    "tech_infra": [
        "devops engineer",
        "cloud engineer",
        "SRE engineer",
        "platform engineer",
        "infrastructure engineer",
        "Kubernetes engineer",
        "AWS architect",
        "network engineer",
        "systems administrator",
        "cybersecurity engineer",
    ],
    "tech_product": [
        "product manager",
        "product owner",
        "scrum master",
        "agile coach",
        "technical project manager",
        "IT project manager",
        "business analyst",
        "functional analyst",
        "solution architect",
    ],
    "tech_design": [
        "UX designer",
        "UI designer",
        "UX researcher",
        "product designer",
        "graphic designer",
        "web designer",
        "motion designer",
    ],
    "tech_security": [
        "cybersecurity analyst",
        "penetration tester",
        "security engineer",
        "CISO",
        "SOC analyst",
        "information security",
    ],
    "finance_banking": [
        "financial analyst",
        "comptable",
        "contrôleur de gestion",
        "auditeur",
        "risk manager",
        "trésorier",
        "analyste crédit",
        "conseiller bancaire",
        "gestionnaire de patrimoine",
        "compliance officer",
        "quant analyst",
    ],
    "marketing_sales": [
        "marketing manager",
        "growth hacker",
        "SEO specialist",
        "content manager",
        "community manager",
        "chef de projet marketing",
        "commercial",
        "ingénieur commercial",
        "account manager",
        "business developer",
        "sales manager",
        "CRM manager",
    ],
    "hr_legal": [
        "RH manager",
        "chargé de recrutement",
        "talent acquisition",
        "responsable formation",
        "juriste",
        "avocat",
        "paralegal",
        "responsable juridique",
        "gestionnaire paie",
    ],
    "engineering_industry": [
        "ingénieur mécanique",
        "ingénieur électronique",
        "ingénieur électrique",
        "ingénieur industriel",
        "ingénieur R&D",
        "ingénieur qualité",
        "ingénieur production",
        "ingénieur maintenance",
        "ingénieur automatisme",
        "ingénieur civil",
        "ingénieur génie chimique",
        "ingénieur aéronautique",
    ],
    "supply_chain": [
        "supply chain manager",
        "logisticien",
        "acheteur",
        "responsable achats",
        "gestionnaire stocks",
        "responsable entrepôt",
        "transport manager",
        "chef de projet logistique",
    ],
    "healthcare": [
        "médecin",
        "infirmier",
        "pharmacien",
        "sage-femme",
        "kinésithérapeute",
        "ergothérapeute",
        "psychologue",
        "technicien de laboratoire",
        "directeur établissement santé",
        "data scientist santé",
    ],
    "education_research": [
        "enseignant",
        "formateur",
        "chercheur",
        "ingénieur de recherche",
        "chef de projet R&D",
        "consultant en formation",
        "chargé d'études",
    ],
    "consulting_management": [
        "consultant",
        "consultant IT",
        "consultant stratégie",
        "manager conseil",
        "directeur général",
        "directeur opérations",
        "chef de projet",
        "responsable transformation digitale",
    ],
    "construction_real_estate": [
        "ingénieur BTP",
        "chef de chantier",
        "conducteur de travaux",
        "architecte",
        "responsable immobilier",
        "property manager",
        "asset manager",
    ],
    "communication_media": [
        "journaliste",
        "chargé de communication",
        "relations presse",
        "rédacteur",
        "attaché de presse",
        "directeur artistique",
    ],
}

# Flat list for direct use in ingestion
SEED_KEYWORDS: list[str] = [
    kw
    for keywords in SEED_KEYWORDS_BY_DOMAIN.values()
    for kw in keywords
]